<a href="https://colab.research.google.com/github/Sue200/Numerical-Methods/blob/main/CSE317_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



#**Numerical Lab Assignment-1**

**Name:** Suhaila 

**ID:**   1910496

In [ ]:
import numpy as np

**Q1:** Find the sum and mean of the 2nd row for a random matrix of size 5 X 10

In [ ]:
a = np.random.randint(1,10,(5,10))
print(a)
print("sum:",a[1,:].sum())
print("mean:", a[1,:].mean())


[[8 9 3 2 6 4 5 5 3 5]
 [9 9 4 1 1 3 4 7 6 2]
 [4 9 9 4 7 8 3 4 4 7]
 [7 3 5 2 6 4 2 5 6 8]
 [2 6 8 2 8 4 8 1 1 4]]
sum: 46
mean: 4.6


'\nprint(a)\nprint("-----------")\nb=np.array(a[1,:])\nprint(b)\nprint("-----------")\n\nsums = 0\nfor element in b:\n  sums = sums + element\nprint("Sum of 2nd row:",sums)\nprint("------------")\nmean = sums/b.size\nprint("Mean:",mean)\n'

**Q2:** Find the sum and mean of all the rows for a random matrix of size 5 X 10


In [ ]:
a = np.random.randint(1,10,(5,10))
print(a)
print("Sum:",a.sum(axis=1))
print("Mean:",a.mean(axis=1))


[[8 2 5 6 1 4 8 3 6 1]
 [6 5 5 4 2 8 8 3 2 8]
 [6 9 2 1 5 6 8 7 5 7]
 [4 4 2 6 1 9 2 4 8 1]
 [6 3 6 6 4 1 3 7 6 4]]
Sum: [44 51 56 41 46]
Mean: [4.4 5.1 5.6 4.1 4.6]


**Q3** Find the mean(v) where v is a vector without using the mean(). Let’s assume v is a
20 X 1 random vector

In [ ]:
a = np.random.randint(1,10,(20,1))
print(a)
x = a.sum()
m = x/a.size
print("mean(v):",m)



[[9]
 [7]
 [2]
 [8]
 [9]
 [3]
 [6]
 [9]
 [3]
 [7]
 [6]
 [1]
 [2]
 [3]
 [6]
 [6]
 [8]
 [6]
 [9]
 [9]]
mean(v): 5.95


**Q4:** : Generate the vector [25 16 9 4 1] using a for loop using horizontal concatenating.

**Q5:** Given a vector like [1 4 9 16 25], output a vector containing only the elements that
are even, i.e., [4 16]

In [ ]:
a = np.array([1,4,9,1,6,25])
print(a)
print("-------")
bool_idx = (a%2 == 0)
print(a[bool_idx])

[ 1  4  9  1  6 25]
-------
[4 6]


**Q6:** Write a function that performs that task in exercise 5 and also returns the number
of elements in the vector.

In [ ]:
def evenVector(a):
  bool_idx = (a%2 == 0)
  b = np.array(a[bool_idx])
  print(b)
  return b.size
a = np.array([1,4,9,1,6,25])
siz = evenVector(a)
print(siz)

[4 6]
2
