<a href="https://colab.research.google.com/github/Sue200/Numerical-Methods/blob/main/CSE317_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



#**Numerical Lab Assignment-1**

**Name:** Suhaila 

**ID:**   1910496

In [1]:
import numpy as np

**Q1:** Find the sum and mean of the 2nd row for a random matrix of size 5 X 10

In [17]:
a = np.random.randint(1,10,(5,10))
print(a)
print("sum:",a[1,:].sum())
print("mean:", a[1,:].mean())


[[3 7 6 6 5 4 7 4 5 6]
 [6 5 5 3 7 8 3 9 5 4]
 [8 9 5 2 5 2 8 9 4 7]
 [1 8 9 9 8 7 1 6 5 3]
 [8 6 2 9 2 2 8 4 2 1]]
sum: 55
mean: 5.5


**Q2:** Find the sum and mean of all the rows for a random matrix of size 5 X 10


In [18]:
a = np.random.randint(1,10,(5,10))
print(a)
print("Sum:",a.sum(axis=1))
print("Mean:",a.mean(axis=1))


[[1 7 9 5 4 2 3 1 9 9]
 [1 4 8 7 7 9 1 4 8 4]
 [8 2 9 6 3 1 9 3 5 6]
 [8 1 9 4 2 5 4 2 1 4]
 [5 9 6 6 7 1 7 3 5 1]]
Sum: [50 53 52 40 50]
Mean: [5.  5.3 5.2 4.  5. ]


**Q3** Find the mean(v) where v is a vector without using the mean(). Let’s assume v is a
20 X 1 random vector

In [33]:
v = np.random.randint(1,10,(20,1))
print(v)
x = v.sum()
m = x/a.size
print("mean(v):",m)



[[3]
 [7]
 [9]
 [7]
 [2]
 [3]
 [2]
 [5]
 [3]
 [3]
 [6]
 [3]
 [4]
 [6]
 [8]
 [7]
 [8]
 [7]
 [6]
 [7]]
mean(v): 5.5


**Q4:** : Generate the vector [25 16 9 4 1] using a for loop using horizontal concatenating.

In [31]:
v = np.array([])
for x in range(1,6):
  a = np.array([x**2])
  v = np.hstack((a,v))
print(v)

[25. 16.  9.  4.  1.]


**Q5:** Given a vector like [1 4 9 16 25], output a vector containing only the elements that
are even, i.e., [4 16]

In [37]:
a = np.array([1,4,9,16,25])
bool_idx = (a%2 == 0)
b = np.array(a[bool_idx])
print(b)

[ 4 16]


**Q6:** Write a function that performs that task in exercise 5 and also returns the number
of elements in the vector.

In [30]:
def evenVector(a):
  bool_idx = (a%2 == 0)
  b = np.array(a[bool_idx])
  return b,b.size
a = np.array([1,4,9,1,16,25])
x = np.array([])
x,y = evenVector(a)
print("vector:",x)
print("Number of elements:",y)

vector: [ 4 16]
Number of elements: 2
